# Generated by Clonehaus Governance Plugin
# Agent Charter v{{charter_version}}
# Ratified by: {{ratified_by}}
# Date: {{ratification_date}}
# Authority Level: {{decision_label}} ({{decision_level}})

"""AutoGen governance template generated from a Clonehaus Agent Charter."""

from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional

from autogen import ConversableAgent


GOVERNANCE_BLOCK = """{{governance_block}}"""


DEFAULT_AUTHORITY_CONTEXT: Dict[str, Any] = {
    "agent_name": "{{agent_name}}",
    "decision_level": "{{decision_level}}",
    "decision_label": "{{decision_label}}",
    "data_ceiling": "{{data_ceiling}}",
    "data_label": "{{data_label}}",
    "comm_scope": "{{comm_scope}}",
    "comm_label": "{{comm_label}}",
    "system_access": "{{system_access}}",
    "system_label": "{{system_label}}",
    "escalation_triggers": """{{escalation_triggers}}""",
    "governance_block": GOVERNANCE_BLOCK,
}


DECISION_RANK = {
    "INFORMATIONAL": 1,
    "ADVISORY": 2,
    "OPERATIONAL": 3,
    "TRANSACTIONAL": 4,
    "STRATEGIC": 5,
}

DATA_RANK = {
    "PUBLIC": 1,
    "INTERNAL": 2,
    "CONFIDENTIAL": 3,
    "RESTRICTED": 4,
}

COMM_RANK = {
    "INTERNAL_ONLY": 1,
    "CLIENT_ROUTINE": 2,
    "ADVISORY": 3,
    "PARTNER": 4,
    "PUBLIC": 5,
    "LEADERSHIP": 6,
}

SYSTEM_RANK = {
    "READ_ONLY": 1,
    "WRITE_LIMITED": 2,
    "WRITE_BROAD": 3,
    "ADMIN": 4,
}


class AuthorityViolation(Exception):
    """Raised when a requested action exceeds the charter."""


class EscalationRequired(Exception):
    """Raised when a human must review the request."""

    def __init__(self, reason: str, context: Optional[Dict[str, Any]] = None):
        super().__init__(reason)
        self.reason = reason
        self.context = context or {}


class GovernanceGuard:
    """Conservative guard used before AutoGen generates a reply."""

    def __init__(self, authority_context: Dict[str, Any]):
        self.authority_context = authority_context
        self.decision_level = authority_context["decision_level"]
        self.data_ceiling = authority_context["data_ceiling"]
        self.comm_scope = authority_context["comm_scope"]
        self.system_access = authority_context["system_access"]
        self.escalation_triggers = self._normalize_triggers(
            authority_context.get("escalation_triggers", [])
        )

    def check_authority(
        self, action: Optional[Dict[str, Any]], context: Optional[Dict[str, Any]] = None
    ) -> None:
        action = action or {}
        context = context or {}
        self._check_decision_authority(action)
        self._check_data_access(action)
        self._check_external_communication(action)
        self._check_system_access(action)
        self._check_escalation_triggers(action, context)

    def escalate(self, reason: str, context: Optional[Dict[str, Any]] = None) -> None:
        raise EscalationRequired(reason, context or {})

    def _check_decision_authority(self, action: Dict[str, Any]) -> None:
        self._assert_within_rank(
            self._clean_value(action.get("decision_level")),
            self.decision_level,
            DECISION_RANK,
            "decision authority",
        )

    def _check_data_access(self, action: Dict[str, Any]) -> None:
        self._assert_within_rank(
            self._clean_value(action.get("data_classification")),
            self.data_ceiling,
            DATA_RANK,
            "data access",
        )

    def _check_external_communication(self, action: Dict[str, Any]) -> None:
        self._assert_within_rank(
            self._clean_value(action.get("recipient_scope")),
            self.comm_scope,
            COMM_RANK,
            "external communication",
        )

    def _check_system_access(self, action: Dict[str, Any]) -> None:
        self._assert_within_rank(
            self._clean_value(action.get("system_access")),
            self.system_access,
            SYSTEM_RANK,
            "system access",
        )

    def _check_escalation_triggers(
        self, action: Dict[str, Any], context: Dict[str, Any]
    ) -> None:
        if action.get("escalates"):
            self.escalate("Action flagged for escalation by caller.", context)
        if action.get("out_of_scope") and "scope boundary" in self._lowered_triggers:
            self.escalate("Escalation trigger matched: scope boundary", context)
        if action.get("ambiguous") and "ambiguity" in self._lowered_triggers:
            self.escalate("Escalation trigger matched: ambiguity", context)
        if action.get("near_authority_limit") and "authority ceiling" in self._lowered_triggers:
            self.escalate("Escalation trigger matched: authority ceiling", context)

    def _assert_within_rank(
        self,
        required_value: str,
        allowed_value: str,
        rank_map: Dict[str, int],
        boundary_name: str,
    ) -> None:
        if not required_value:
            return
        required_rank = rank_map.get(required_value)
        allowed_rank = rank_map.get(self._clean_value(allowed_value))
        if required_rank is None or allowed_rank is None:
            self.escalate(f"Unknown {boundary_name} value.", {"required": required_value})
        if required_rank > allowed_rank:
            raise AuthorityViolation(
                f"Requested {boundary_name} '{required_value}' exceeds '{allowed_value}'."
            )

    @property
    def _lowered_triggers(self) -> List[str]:
        return [trigger.lower() for trigger in self.escalation_triggers]

    @staticmethod
    def _normalize_triggers(raw_triggers: Any) -> List[str]:
        if isinstance(raw_triggers, list):
            return [str(item).strip("- ").strip() for item in raw_triggers if str(item).strip()]
        if isinstance(raw_triggers, str):
            return [
                line.strip("- ").strip()
                for line in raw_triggers.splitlines()
                if line.strip("- ").strip()
            ]
        return []

    @staticmethod
    def _clean_value(value: Any) -> str:
        return str(value or "").strip().upper()


DEFAULT_GOVERNANCE_GUARD = GovernanceGuard(DEFAULT_AUTHORITY_CONTEXT)


def governed_reply(recipient, messages=None, sender=None, config=None):
    """AutoGen reply guard. Return a terminal escalation string on violation."""

    config = config or {}
    messages = messages or []
    guard = config.get("governance_guard", DEFAULT_GOVERNANCE_GUARD)
    action = config.get("action", {})

    last_message = messages[-1] if messages else {}
    if isinstance(last_message, dict):
        context = {
            "sender": getattr(sender, "name", None),
            "recipient": getattr(recipient, "name", None),
            "message": last_message.get("content"),
        }
    else:
        context = {"sender": getattr(sender, "name", None), "recipient": getattr(recipient, "name", None)}

    try:
        guard.check_authority(action, context)
    except (AuthorityViolation, EscalationRequired) as exc:
        return f"ESCALATION: {exc}"

    return None


def create_governed_agent(authority_context: Optional[Dict[str, Any]] = None) -> ConversableAgent:
    """Create a ConversableAgent with a governance reply guard."""

    merged_context = dict(DEFAULT_AUTHORITY_CONTEXT)
    if authority_context:
        merged_context.update(authority_context)

    guard = GovernanceGuard(merged_context)

    return ConversableAgent(
        name=merged_context["agent_name"],
        system_message=merged_context["governance_block"],
        llm_config={"model": "claude-sonnet-4"},
        human_input_mode="NEVER",
        is_termination_msg=lambda msg: "ESCALATION" in str(
            msg.get("content") if isinstance(msg, dict) else msg
        ),
        reply_func_list=[
            {
                "reply_func": governed_reply,
                "config": {"governance_guard": guard},
            }
        ],
    )


if __name__ == "__main__":
    agent = create_governed_agent()
    print(agent.system_message)
