# Generated by Clonehaus Governance Plugin
# Agent Charter v{{charter_version}}
# Ratified by: {{ratified_by}}
# Date: {{ratification_date}}
# Authority Level: {{decision_label}} ({{decision_level}})

"""CrewAI governance template generated from a Clonehaus Agent Charter."""

from __future__ import annotations

from typing import Any, Callable, Iterable, List, Optional

from crewai import Agent, Crew, Task


GOVERNANCE_BLOCK = """{{governance_block}}"""

DECISION_LEVEL = "{{decision_level}}"
DECISION_LABEL = "{{decision_label}}"
AGENT_NAME = "{{agent_name}}"


def _decision_rank(level: str) -> int:
    return {
        "INFORMATIONAL": 1,
        "ADVISORY": 2,
        "OPERATIONAL": 3,
        "TRANSACTIONAL": 4,
        "STRATEGIC": 5,
    }.get(str(level).strip().upper(), 1)


def _limit_tools(tools: Optional[Iterable[Callable[..., Any]]]) -> List[Callable[..., Any]]:
    """Restrict available tools so lower-authority agents stay narrow."""

    tool_list = list(tools or [])
    rank = _decision_rank(DECISION_LEVEL)

    if rank <= 1:
        return []
    if rank == 2:
        return tool_list[:1]
    if rank == 3:
        return tool_list[:2]
    return tool_list


def create_governed_agent(
    tools: Optional[Iterable[Callable[..., Any]]] = None,
) -> Agent:
    """Create a CrewAI agent whose persona is anchored to the charter."""

    limited_tools = _limit_tools(tools)
    decision_rank = _decision_rank(DECISION_LEVEL)

    # L1-L2 agents cannot delegate because their scope is tightly bounded.
    allow_delegation = decision_rank >= 3

    backstory = (
        f"You are {AGENT_NAME}, a governed CrewAI agent.\n\n"
        "You must operate inside the following authority boundaries at all times.\n\n"
        f"{GOVERNANCE_BLOCK}\n\n"
        "If a request exceeds your scope or triggers escalation, stop and hand off "
        "to a human reviewer."
    )

    return Agent(
        role=AGENT_NAME,
        goal=f"Operate within {DECISION_LABEL} authority",
        backstory=backstory,
        tools=limited_tools,
        verbose=True,
        allow_delegation=allow_delegation,
    )


if __name__ == "__main__":
    def summarize_contract(text: str) -> str:
        """Example tool. Replace with real CrewAI tools after export."""

        return f"Summary requested for: {text[:80]}"

    agent = create_governed_agent(tools=[summarize_contract])

    task = Task(
        description="Review the supplied contract and summarize the main risks.",
        expected_output="A concise risk summary that stays within charter boundaries.",
        agent=agent,
    )

    crew = Crew(agents=[agent], tasks=[task], verbose=True)
    print(crew)
