# Generated by Clonehaus Governance Plugin
# Agent Charter: {{agent_name}}
# Ratified by: {{ratified_by}}
# Ratification date: {{ratification_date}}
# Charter version: {{charter_version}}
# Decision authority: {{decision_level}}

"""LangChain governance template generated from a Clonehaus Agent Charter.

This file is a template. The /clonehaus:export-context command substitutes the
{{placeholder}} values with the current charter and emits a ready-to-run file.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Iterable, List, Optional

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_anthropic import ChatAnthropic


GOVERNANCE_BLOCK = """<agent_authority>
DECISION AUTHORITY: {{decision_label}} ({{decision_level}})
- Can: {{can_do}}
- Cannot: {{cannot_do}}

DATA ACCESS: {{data_label}} ({{data_ceiling}})
- Can access: {{allowed_data}}
- Cannot access: {{restricted_data}}

EXTERNAL COMMUNICATION: {{comm_label}} ({{comm_scope}})
- Can communicate with: {{allowed_recipients}}
- Cannot communicate with: {{restricted_recipients}}

SYSTEM ACCESS: {{system_label}} ({{system_access}})
- Can interact with: {{allowed_systems}}
- Cannot interact with: {{restricted_systems}}

ESCALATION TRIGGERS:
{{escalation_triggers}}

EAPP PRINCIPLES:
1. Transparency: Always explain reasoning
2. Escalation: When in doubt, escalate
3. Scope Discipline: Stay within boundaries
</agent_authority>"""


DEFAULT_AUTHORITY_CONTEXT: Dict[str, Any] = {
    "agent_name": "{{agent_name}}",
    "decision_level": "{{decision_level}}",
    "decision_label": "{{decision_label}}",
    "data_ceiling": "{{data_ceiling}}",
    "data_label": "{{data_label}}",
    "comm_scope": "{{comm_scope}}",
    "comm_label": "{{comm_label}}",
    "system_access": "{{system_access}}",
    "system_label": "{{system_label}}",
    "escalation_triggers": """{{escalation_triggers}}""",
    "governance_block": GOVERNANCE_BLOCK,
}


DECISION_RANK = {
    "INFORMATIONAL": 1,
    "ADVISORY": 2,
    "OPERATIONAL": 3,
    "TRANSACTIONAL": 4,
    "STRATEGIC": 5,
}

DATA_RANK = {
    "PUBLIC": 1,
    "INTERNAL": 2,
    "CONFIDENTIAL": 3,
    "RESTRICTED": 4,
}

COMM_RANK = {
    "INTERNAL_ONLY": 1,
    "CLIENT_ROUTINE": 2,
    "ADVISORY": 3,
    "PARTNER": 4,
    "PUBLIC": 5,
    "LEADERSHIP": 6,
}

SYSTEM_RANK = {
    "READ_ONLY": 1,
    "WRITE_LIMITED": 2,
    "WRITE_BROAD": 3,
    "ADMIN": 4,
}


class AuthorityViolation(Exception):
    """Raised when a requested action exceeds the charter's authority."""


class EscalationRequired(Exception):
    """Raised when the action should be handed to a human reviewer."""

    def __init__(self, reason: str, context: Optional[Dict[str, Any]] = None):
        super().__init__(reason)
        self.reason = reason
        self.context = context or {}


class GovernanceGuard:
    """Validates planned agent actions against the exported authority context.

    The guard performs simple pre-execution checks. It is intentionally
    conservative: when the action metadata is ambiguous or hits a defined
    escalation rule, it raises for human review instead of guessing.
    """

    def __init__(self, authority_context: Dict[str, Any]):
        self.authority_context = authority_context
        self.decision_level = authority_context["decision_level"]
        self.data_ceiling = authority_context["data_ceiling"]
        self.comm_scope = authority_context["comm_scope"]
        self.system_access = authority_context["system_access"]
        self.escalation_triggers = self._normalize_triggers(
            authority_context.get("escalation_triggers", [])
        )

    def check_authority(
        self, action: Optional[Dict[str, Any]], context: Optional[Dict[str, Any]] = None
    ) -> None:
        """Validate the requested action against every governance boundary.

        Expected action keys:
        - decision_level
        - data_classification
        - recipient_scope
        - system_access
        - risk_flags
        - stakeholders
        - escalates
        """

        action = action or {}
        context = context or {}

        self._check_decision_authority(action)
        self._check_data_access(action)
        self._check_external_communication(action)
        self._check_system_access(action)
        self._check_escalation_triggers(action, context)

    def escalate(
        self, reason: str, context: Optional[Dict[str, Any]] = None
    ) -> None:
        """Raise a structured escalation instead of silently failing open."""

        details = {
            "reason": reason,
            "authority_context": {
                "decision_level": self.decision_level,
                "data_ceiling": self.data_ceiling,
                "comm_scope": self.comm_scope,
                "system_access": self.system_access,
            },
            "context": context or {},
        }
        raise EscalationRequired(reason, details)

    def _check_decision_authority(self, action: Dict[str, Any]) -> None:
        required_level = self._clean_value(action.get("decision_level"))
        if not required_level:
            return
        self._assert_within_rank(
            required_level,
            self.decision_level,
            DECISION_RANK,
            "decision authority",
        )

    def _check_data_access(self, action: Dict[str, Any]) -> None:
        required_level = self._clean_value(action.get("data_classification"))
        if not required_level:
            return
        self._assert_within_rank(
            required_level,
            self.data_ceiling,
            DATA_RANK,
            "data access",
        )

    def _check_external_communication(self, action: Dict[str, Any]) -> None:
        required_scope = self._clean_value(action.get("recipient_scope"))
        if not required_scope:
            return
        self._assert_within_rank(
            required_scope,
            self.comm_scope,
            COMM_RANK,
            "external communication",
        )

    def _check_system_access(self, action: Dict[str, Any]) -> None:
        required_access = self._clean_value(action.get("system_access"))
        if not required_access:
            return
        self._assert_within_rank(
            required_access,
            self.system_access,
            SYSTEM_RANK,
            "system access",
        )

    def _check_escalation_triggers(
        self, action: Dict[str, Any], context: Dict[str, Any]
    ) -> None:
        """Escalate on explicit trigger signals from the calling application."""

        if action.get("escalates"):
            self.escalate("Action flagged for escalation by caller.", context)

        risk_flags = [self._clean_text(flag) for flag in action.get("risk_flags", [])]
        stakeholders = [self._clean_text(item) for item in action.get("stakeholders", [])]

        trigger_checks = {
            "scope boundary": bool(action.get("out_of_scope")),
            "risk or sensitivity": any(risk_flags),
            "ambiguity": bool(action.get("ambiguous")),
            "key stakeholder": any(stakeholders),
            "authority ceiling": bool(action.get("near_authority_limit")),
        }

        for trigger in self.escalation_triggers:
            lowered = trigger.lower()
            if lowered in trigger_checks and trigger_checks[lowered]:
                self.escalate(f"Escalation trigger matched: {trigger}", context)

            # Custom numeric triggers can be passed in as exact match keys by the caller.
            if lowered not in trigger_checks and lowered in self._context_keys(action, context):
                self.escalate(f"Custom escalation trigger matched: {trigger}", context)

    def _assert_within_rank(
        self,
        required_value: str,
        allowed_value: str,
        rank_map: Dict[str, int],
        boundary_name: str,
    ) -> None:
        required_rank = rank_map.get(required_value)
        allowed_rank = rank_map.get(self._clean_value(allowed_value))

        if required_rank is None:
            self.escalate(
                f"Unknown requested {boundary_name} value: {required_value}",
                {"boundary": boundary_name},
            )
        if allowed_rank is None:
            self.escalate(
                f"Unknown charter {boundary_name} value: {allowed_value}",
                {"boundary": boundary_name},
            )

        if required_rank > allowed_rank:
            raise AuthorityViolation(
                f"Requested {boundary_name} '{required_value}' exceeds "
                f"allowed '{allowed_value}'."
            )

    @staticmethod
    def _normalize_triggers(raw_triggers: Any) -> List[str]:
        if isinstance(raw_triggers, list):
            return [str(trigger).strip("- ").strip() for trigger in raw_triggers if str(trigger).strip()]
        if isinstance(raw_triggers, str):
            lines = [line.strip("- ").strip() for line in raw_triggers.splitlines()]
            return [line for line in lines if line]
        return []

    @staticmethod
    def _clean_value(value: Any) -> str:
        return str(value or "").strip().upper()

    @staticmethod
    def _clean_text(value: Any) -> str:
        return str(value or "").strip().lower()

    @staticmethod
    def _context_keys(action: Dict[str, Any], context: Dict[str, Any]) -> Iterable[str]:
        combined = {str(key).strip().lower() for key in action.keys()}
        combined.update(str(key).strip().lower() for key in context.keys())
        return combined


def create_governed_agent(
    authority_context: Optional[Dict[str, Any]] = None,
    *,
    anthropic_api_key: Optional[str] = None,
    model: str = "claude-sonnet-4",
    temperature: float = 0.0,
):
    """Create a governed LangChain runnable backed by ChatAnthropic.

    The returned callable enforces governance checks before invoking the model.
    The caller can pass action metadata for stronger enforcement, for example:

    {
        "decision_level": "ADVISORY",
        "data_classification": "CONFIDENTIAL",
        "recipient_scope": "INTERNAL_ONLY",
        "system_access": "READ_ONLY",
        "risk_flags": [],
    }
    """

    merged_context = dict(DEFAULT_AUTHORITY_CONTEXT)
    if authority_context:
        merged_context.update(authority_context)

    prompt = PromptTemplate(
        input_variables=["user_input"],
        partial_variables={"governance_block": merged_context["governance_block"]},
        template=(
            "You are {agent_name}.\n\n"
            "{governance_block}\n\n"
            "Follow the authority block exactly. If the request exceeds scope, "
            "state that human review is required.\n\n"
            "User request:\n{user_input}\n"
        ),
    ).partial(agent_name=merged_context["agent_name"])

    llm = ChatAnthropic(
        model=model,
        temperature=temperature,
        anthropic_api_key=anthropic_api_key,
    )
    chain = LLMChain(llm=llm, prompt=prompt)
    guard = GovernanceGuard(merged_context)

    def governed_run(
        user_input: str,
        *,
        action: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Run the chain only after the governance guard clears the action."""

        guard.check_authority(action or {}, context or {})
        return chain.predict(user_input=user_input)

    return governed_run


if __name__ == "__main__":
    # This example shows how the exported file can be wired into an app or CLI.
    governed_agent = create_governed_agent(
        {
            "agent_name": "{{agent_name}}",
            "decision_level": "{{decision_level}}",
            "decision_label": "{{decision_label}}",
            "data_ceiling": "{{data_ceiling}}",
            "data_label": "{{data_label}}",
            "comm_scope": "{{comm_scope}}",
            "comm_label": "{{comm_label}}",
            "system_access": "{{system_access}}",
            "system_label": "{{system_label}}",
            "escalation_triggers": """{{escalation_triggers}}""",
            "governance_block": GOVERNANCE_BLOCK,
        }
    )

    sample_action = {
        "decision_level": "{{decision_level}}",
        "data_classification": "{{data_ceiling}}",
        "recipient_scope": "{{comm_scope}}",
        "system_access": "{{system_access}}",
        "risk_flags": [],
    }

    try:
        result = governed_agent(
            "Review this NDA and summarize the main commercial risks.",
            action=sample_action,
            context={"request_id": "demo"},
        )
        print(result)
    except AuthorityViolation as exc:
        print(f"Authority violation: {exc}")
    except EscalationRequired as exc:
        print("Escalation required:")
        print(json.dumps(exc.context, indent=2))
