# Generated by Clonehaus Governance Plugin
# Agent Charter v{{charter_version}}
# Ratified by: {{ratified_by}}
# Date: {{ratification_date}}
# Authority Level: {{decision_label}} ({{decision_level}})

"""LangGraph governance template generated from a Clonehaus Agent Charter."""

from __future__ import annotations

import json
from typing import Any, Dict, Iterable, List, Optional, TypedDict

from langchain_anthropic import ChatAnthropic
from langgraph.graph import END, StateGraph


GOVERNANCE_BLOCK = """{{governance_block}}"""


DEFAULT_AUTHORITY_CONTEXT: Dict[str, Any] = {
    "agent_name": "{{agent_name}}",
    "decision_level": "{{decision_level}}",
    "decision_label": "{{decision_label}}",
    "data_ceiling": "{{data_ceiling}}",
    "data_label": "{{data_label}}",
    "comm_scope": "{{comm_scope}}",
    "comm_label": "{{comm_label}}",
    "system_access": "{{system_access}}",
    "system_label": "{{system_label}}",
    "escalation_triggers": """{{escalation_triggers}}""",
    "governance_block": GOVERNANCE_BLOCK,
}


DECISION_RANK = {
    "INFORMATIONAL": 1,
    "ADVISORY": 2,
    "OPERATIONAL": 3,
    "TRANSACTIONAL": 4,
    "STRATEGIC": 5,
}

DATA_RANK = {
    "PUBLIC": 1,
    "INTERNAL": 2,
    "CONFIDENTIAL": 3,
    "RESTRICTED": 4,
}

COMM_RANK = {
    "INTERNAL_ONLY": 1,
    "CLIENT_ROUTINE": 2,
    "ADVISORY": 3,
    "PARTNER": 4,
    "PUBLIC": 5,
    "LEADERSHIP": 6,
}

SYSTEM_RANK = {
    "READ_ONLY": 1,
    "WRITE_LIMITED": 2,
    "WRITE_BROAD": 3,
    "ADMIN": 4,
}


class AuthorityViolation(Exception):
    """Raised when a requested action exceeds the charter."""


class EscalationRequired(Exception):
    """Raised when a human must review the request."""

    def __init__(self, reason: str, context: Optional[Dict[str, Any]] = None):
        super().__init__(reason)
        self.reason = reason
        self.context = context or {}


class GovernanceGuard:
    """Conservative preflight guard shared across framework templates."""

    def __init__(self, authority_context: Dict[str, Any]):
        self.authority_context = authority_context
        self.decision_level = authority_context["decision_level"]
        self.data_ceiling = authority_context["data_ceiling"]
        self.comm_scope = authority_context["comm_scope"]
        self.system_access = authority_context["system_access"]
        self.escalation_triggers = self._normalize_triggers(
            authority_context.get("escalation_triggers", [])
        )

    def check_authority(
        self, action: Optional[Dict[str, Any]], context: Optional[Dict[str, Any]] = None
    ) -> None:
        action = action or {}
        context = context or {}

        self._check_decision_authority(action)
        self._check_data_access(action)
        self._check_external_communication(action)
        self._check_system_access(action)
        self._check_escalation_triggers(action, context)

    def escalate(self, reason: str, context: Optional[Dict[str, Any]] = None) -> None:
        raise EscalationRequired(
            reason,
            {
                "reason": reason,
                "authority_context": {
                    "decision_level": self.decision_level,
                    "data_ceiling": self.data_ceiling,
                    "comm_scope": self.comm_scope,
                    "system_access": self.system_access,
                },
                "context": context or {},
            },
        )

    def _check_decision_authority(self, action: Dict[str, Any]) -> None:
        required = self._clean_value(action.get("decision_level"))
        if required:
            self._assert_within_rank(
                required, self.decision_level, DECISION_RANK, "decision authority"
            )

    def _check_data_access(self, action: Dict[str, Any]) -> None:
        required = self._clean_value(action.get("data_classification"))
        if required:
            self._assert_within_rank(required, self.data_ceiling, DATA_RANK, "data access")

    def _check_external_communication(self, action: Dict[str, Any]) -> None:
        required = self._clean_value(action.get("recipient_scope"))
        if required:
            self._assert_within_rank(
                required, self.comm_scope, COMM_RANK, "external communication"
            )

    def _check_system_access(self, action: Dict[str, Any]) -> None:
        required = self._clean_value(action.get("system_access"))
        if required:
            self._assert_within_rank(required, self.system_access, SYSTEM_RANK, "system access")

    def _check_escalation_triggers(
        self, action: Dict[str, Any], context: Dict[str, Any]
    ) -> None:
        if action.get("escalates"):
            self.escalate("Action flagged for escalation by caller.", context)

        risk_flags = [self._clean_text(flag) for flag in action.get("risk_flags", [])]
        stakeholders = [self._clean_text(item) for item in action.get("stakeholders", [])]

        trigger_checks = {
            "scope boundary": bool(action.get("out_of_scope")),
            "risk or sensitivity": any(risk_flags),
            "ambiguity": bool(action.get("ambiguous")),
            "key stakeholder": any(stakeholders),
            "authority ceiling": bool(action.get("near_authority_limit")),
        }

        for trigger in self.escalation_triggers:
            lowered = trigger.lower()
            if lowered in trigger_checks and trigger_checks[lowered]:
                self.escalate(f"Escalation trigger matched: {trigger}", context)
            if lowered not in trigger_checks and lowered in self._context_keys(action, context):
                self.escalate(f"Custom escalation trigger matched: {trigger}", context)

    def _assert_within_rank(
        self,
        required_value: str,
        allowed_value: str,
        rank_map: Dict[str, int],
        boundary_name: str,
    ) -> None:
        required_rank = rank_map.get(required_value)
        allowed_rank = rank_map.get(self._clean_value(allowed_value))
        if required_rank is None:
            self.escalate(f"Unknown requested {boundary_name}: {required_value}")
        if allowed_rank is None:
            self.escalate(f"Unknown charter {boundary_name}: {allowed_value}")
        if required_rank > allowed_rank:
            raise AuthorityViolation(
                f"Requested {boundary_name} '{required_value}' exceeds '{allowed_value}'."
            )

    @staticmethod
    def _normalize_triggers(raw_triggers: Any) -> List[str]:
        if isinstance(raw_triggers, list):
            return [str(item).strip("- ").strip() for item in raw_triggers if str(item).strip()]
        if isinstance(raw_triggers, str):
            lines = [line.strip("- ").strip() for line in raw_triggers.splitlines()]
            return [line for line in lines if line]
        return []

    @staticmethod
    def _clean_value(value: Any) -> str:
        return str(value or "").strip().upper()

    @staticmethod
    def _clean_text(value: Any) -> str:
        return str(value or "").strip().lower()

    @staticmethod
    def _context_keys(action: Dict[str, Any], context: Dict[str, Any]) -> Iterable[str]:
        keys = {str(key).strip().lower() for key in action.keys()}
        keys.update(str(key).strip().lower() for key in context.keys())
        return keys


class AgentState(TypedDict, total=False):
    """State carried through the graph."""

    query: str
    context: Dict[str, Any]
    response: str
    escalation: Dict[str, Any]


def governance_checkpoint(
    state: AgentState, authority_context: Optional[Dict[str, Any]] = None
) -> AgentState:
    """Validate state before any model call is made."""

    merged_context = dict(DEFAULT_AUTHORITY_CONTEXT)
    if authority_context:
        merged_context.update(authority_context)

    guard = GovernanceGuard(merged_context)
    execution_context = dict(state.get("context", {}))
    action = execution_context.get("action", {})

    try:
        guard.check_authority(action, execution_context)
    except AuthorityViolation as exc:
        return {
            "escalation": {"required": True, "reason": str(exc)},
            "response": f"ESCALATION: {exc}",
        }
    except EscalationRequired as exc:
        return {
            "escalation": {"required": True, "reason": exc.reason, "context": exc.context},
            "response": f"ESCALATION: {exc.reason}",
        }

    return {"escalation": {"required": False}}


def llm_call(
    state: AgentState,
    authority_context: Optional[Dict[str, Any]] = None,
    *,
    anthropic_api_key: Optional[str] = None,
    model: str = "claude-sonnet-4",
    temperature: float = 0.0,
) -> AgentState:
    """Call Claude with the governance block embedded in the prompt."""

    merged_context = dict(DEFAULT_AUTHORITY_CONTEXT)
    if authority_context:
        merged_context.update(authority_context)

    llm = ChatAnthropic(
        model=model,
        temperature=temperature,
        anthropic_api_key=anthropic_api_key,
    )
    prompt = (
        f"You are {merged_context['agent_name']}.\n\n"
        f"{merged_context['governance_block']}\n\n"
        f"Follow the authority block exactly.\n\n"
        f"User request:\n{state.get('query', '')}"
    )
    result = llm.invoke(prompt)
    content = result.content if hasattr(result, "content") else str(result)
    if isinstance(content, list):
        content = "\n".join(str(item) for item in content)
    return {"response": str(content)}


def create_governed_agent(
    authority_context: Optional[Dict[str, Any]] = None,
    *,
    anthropic_api_key: Optional[str] = None,
    model: str = "claude-sonnet-4",
    temperature: float = 0.0,
):
    """Build and compile the LangGraph workflow."""

    def checkpoint_node(state: AgentState) -> AgentState:
        return governance_checkpoint(state, authority_context)

    def llm_node(state: AgentState) -> AgentState:
        return llm_call(
            state,
            authority_context,
            anthropic_api_key=anthropic_api_key,
            model=model,
            temperature=temperature,
        )

    def route_after_governance(state: AgentState) -> str:
        escalation = state.get("escalation", {})
        return END if escalation.get("required") else "llm"

    graph = StateGraph(AgentState)
    graph.add_node("governance_check", checkpoint_node)
    graph.add_node("llm", llm_node)
    graph.set_entry_point("governance_check")
    graph.add_conditional_edges("governance_check", route_after_governance)
    graph.add_edge("llm", END)
    return graph.compile()


if __name__ == "__main__":
    workflow = create_governed_agent(
        {
            "agent_name": "{{agent_name}}",
            "decision_level": "{{decision_level}}",
            "decision_label": "{{decision_label}}",
            "data_ceiling": "{{data_ceiling}}",
            "data_label": "{{data_label}}",
            "comm_scope": "{{comm_scope}}",
            "comm_label": "{{comm_label}}",
            "system_access": "{{system_access}}",
            "system_label": "{{system_label}}",
            "escalation_triggers": """{{escalation_triggers}}""",
            "governance_block": GOVERNANCE_BLOCK,
        }
    )

    result = workflow.invoke(
        {
            "query": "Review this NDA and summarize the commercial risks.",
            "context": {
                "action": {
                    "decision_level": "{{decision_level}}",
                    "data_classification": "{{data_ceiling}}",
                    "recipient_scope": "{{comm_scope}}",
                    "system_access": "{{system_access}}",
                }
            },
        }
    )
    print(json.dumps(result, indent=2, default=str))
