// Generated by Clonehaus Governance Plugin
// Agent Charter v{{charter_version}}
// Ratified by: {{ratified_by}}
// Date: {{ratification_date}}
// Authority Level: {{decision_label}} ({{decision_level}})

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Filters;

namespace Clonehaus.Governance;

public static class GovernanceConstants
{
    public const string GovernanceBlock = @"{{governance_block}}";
}

public sealed class AuthorityContext
{
    public string AgentName { get; init; } = "{{agent_name}}";
    public string DecisionLevel { get; init; } = "{{decision_level}}";
    public string DecisionLabel { get; init; } = "{{decision_label}}";
    public string DataCeiling { get; init; } = "{{data_ceiling}}";
    public string DataLabel { get; init; } = "{{data_label}}";
    public string CommScope { get; init; } = "{{comm_scope}}";
    public string CommLabel { get; init; } = "{{comm_label}}";
    public string SystemAccess { get; init; } = "{{system_access}}";
    public string SystemLabel { get; init; } = "{{system_label}}";
    public string EscalationTriggers { get; init; } = @"{{escalation_triggers}}";
}

public sealed class AuthorityViolationException : Exception
{
    public AuthorityViolationException(string message) : base(message)
    {
    }
}

public sealed class EscalationRequiredException : Exception
{
    public EscalationRequiredException(string message) : base(message)
    {
    }
}

public sealed class GovernanceGuard
{
    private static readonly Dictionary<string, int> DecisionRank = new(StringComparer.OrdinalIgnoreCase)
    {
        ["INFORMATIONAL"] = 1,
        ["ADVISORY"] = 2,
        ["OPERATIONAL"] = 3,
        ["TRANSACTIONAL"] = 4,
        ["STRATEGIC"] = 5,
    };

    private static readonly Dictionary<string, int> DataRank = new(StringComparer.OrdinalIgnoreCase)
    {
        ["PUBLIC"] = 1,
        ["INTERNAL"] = 2,
        ["CONFIDENTIAL"] = 3,
        ["RESTRICTED"] = 4,
    };

    private static readonly Dictionary<string, int> CommRank = new(StringComparer.OrdinalIgnoreCase)
    {
        ["INTERNAL_ONLY"] = 1,
        ["CLIENT_ROUTINE"] = 2,
        ["ADVISORY"] = 3,
        ["PARTNER"] = 4,
        ["PUBLIC"] = 5,
        ["LEADERSHIP"] = 6,
    };

    private static readonly Dictionary<string, int> SystemRank = new(StringComparer.OrdinalIgnoreCase)
    {
        ["READ_ONLY"] = 1,
        ["WRITE_LIMITED"] = 2,
        ["WRITE_BROAD"] = 3,
        ["ADMIN"] = 4,
    };

    private readonly AuthorityContext _authorityContext;
    private readonly HashSet<string> _triggers;

    public GovernanceGuard(AuthorityContext authorityContext)
    {
        _authorityContext = authorityContext;
        _triggers = authorityContext.EscalationTriggers
            .Split(new[] { '\n', ',' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(item => item.Trim().TrimStart('-').Trim().ToLowerInvariant())
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .ToHashSet();
    }

    public void CheckAuthority(IDictionary<string, object?> action)
    {
        CheckRank(action, "decision_level", _authorityContext.DecisionLevel, DecisionRank, "decision authority");
        CheckRank(action, "data_classification", _authorityContext.DataCeiling, DataRank, "data access");
        CheckRank(action, "recipient_scope", _authorityContext.CommScope, CommRank, "external communication");
        CheckRank(action, "system_access", _authorityContext.SystemAccess, SystemRank, "system access");

        if (action.TryGetValue("escalates", out var escalatesValue) && escalatesValue is true)
        {
            Escalate("Action flagged for escalation by caller.");
        }

        if (_triggers.Contains("scope boundary") && action.TryGetValue("out_of_scope", out var outOfScope) && outOfScope is true)
        {
            Escalate("Escalation trigger matched: scope boundary");
        }
    }

    public void Escalate(string reason)
    {
        throw new EscalationRequiredException(reason);
    }

    private static void CheckRank(
        IDictionary<string, object?> action,
        string key,
        string allowedValue,
        IDictionary<string, int> rankMap,
        string boundaryName)
    {
        if (!action.TryGetValue(key, out var requestedValue) || requestedValue is null)
        {
            return;
        }

        var requested = requestedValue.ToString()?.Trim().ToUpperInvariant();
        var allowed = allowedValue.Trim().ToUpperInvariant();

        if (string.IsNullOrWhiteSpace(requested))
        {
            return;
        }

        if (!rankMap.TryGetValue(requested, out var requestedRank) || !rankMap.TryGetValue(allowed, out var allowedRank))
        {
            throw new EscalationRequiredException($"Unknown {boundaryName} value.");
        }

        if (requestedRank > allowedRank)
        {
            throw new AuthorityViolationException(
                $"Requested {boundaryName} '{requested}' exceeds '{allowed}'.");
        }
    }
}

public sealed class ClonehausGovernanceFilter : IFunctionInvocationFilter
{
    private readonly GovernanceGuard _guard;

    public ClonehausGovernanceFilter(AuthorityContext authorityContext)
    {
        _guard = new GovernanceGuard(authorityContext);
    }

    public async Task OnFunctionInvocationAsync(FunctionInvocationContext context, Func<FunctionInvocationContext, Task> next)
    {
        var action = new Dictionary<string, object?>
        {
            ["decision_level"] = context.Arguments.TryGetValue("decision_level", out var decision) ? decision : null,
            ["data_classification"] = context.Arguments.TryGetValue("data_classification", out var data) ? data : null,
            ["recipient_scope"] = context.Arguments.TryGetValue("recipient_scope", out var comm) ? comm : null,
            ["system_access"] = context.Arguments.TryGetValue("system_access", out var system) ? system : null,
            ["out_of_scope"] = context.Arguments.TryGetValue("out_of_scope", out var outOfScope) ? outOfScope : null,
            ["escalates"] = context.Arguments.TryGetValue("escalates", out var escalates) ? escalates : null,
        };

        try
        {
            _guard.CheckAuthority(action);
        }
        catch (AuthorityViolationException ex)
        {
            context.Result = new FunctionResult(context.Result?.Function, $"ESCALATION: {ex.Message}", context.Result?.Metadata);
            return;
        }
        catch (EscalationRequiredException ex)
        {
            context.Result = new FunctionResult(context.Result?.Function, $"ESCALATION: {ex.Message}", context.Result?.Metadata);
            return;
        }

        await next(context);
    }
}

// Usage example:
// var builder = Kernel.CreateBuilder();
// var kernel = builder.Build();
// var authorityContext = new AuthorityContext();
// kernel.FunctionInvocationFilters.Add(new ClonehausGovernanceFilter(authorityContext));
