# Generated by Clonehaus Governance Plugin
# Agent Charter v{{charter_version}}
# Ratified by: {{ratified_by}}
# Date: {{ratification_date}}
# Authority Level: {{decision_label}} ({{decision_level}})

"""Semantic Kernel Python governance filter template."""

from __future__ import annotations

import inspect
from typing import Any, Dict, Iterable, List, Optional

from semantic_kernel import Kernel
from semantic_kernel.filters import IFunctionInvocationFilter


GOVERNANCE_BLOCK = """{{governance_block}}"""


DEFAULT_AUTHORITY_CONTEXT: Dict[str, Any] = {
    "agent_name": "{{agent_name}}",
    "decision_level": "{{decision_level}}",
    "decision_label": "{{decision_label}}",
    "data_ceiling": "{{data_ceiling}}",
    "data_label": "{{data_label}}",
    "comm_scope": "{{comm_scope}}",
    "comm_label": "{{comm_label}}",
    "system_access": "{{system_access}}",
    "system_label": "{{system_label}}",
    "escalation_triggers": """{{escalation_triggers}}""",
    "governance_block": GOVERNANCE_BLOCK,
}


DECISION_RANK = {
    "INFORMATIONAL": 1,
    "ADVISORY": 2,
    "OPERATIONAL": 3,
    "TRANSACTIONAL": 4,
    "STRATEGIC": 5,
}

DATA_RANK = {
    "PUBLIC": 1,
    "INTERNAL": 2,
    "CONFIDENTIAL": 3,
    "RESTRICTED": 4,
}

COMM_RANK = {
    "INTERNAL_ONLY": 1,
    "CLIENT_ROUTINE": 2,
    "ADVISORY": 3,
    "PARTNER": 4,
    "PUBLIC": 5,
    "LEADERSHIP": 6,
}

SYSTEM_RANK = {
    "READ_ONLY": 1,
    "WRITE_LIMITED": 2,
    "WRITE_BROAD": 3,
    "ADMIN": 4,
}


class AuthorityViolation(Exception):
    """Raised when a requested function call exceeds the charter."""


class EscalationRequired(Exception):
    """Raised when a human must review the invocation."""

    def __init__(self, reason: str, context: Optional[Dict[str, Any]] = None):
        super().__init__(reason)
        self.reason = reason
        self.context = context or {}


class GovernanceGuard:
    """Shared governance gate for Semantic Kernel invocations."""

    def __init__(self, authority_context: Dict[str, Any]):
        self.authority_context = authority_context
        self.decision_level = authority_context["decision_level"]
        self.data_ceiling = authority_context["data_ceiling"]
        self.comm_scope = authority_context["comm_scope"]
        self.system_access = authority_context["system_access"]
        self.escalation_triggers = self._normalize_triggers(
            authority_context.get("escalation_triggers", [])
        )

    def check_authority(
        self, action: Optional[Dict[str, Any]], context: Optional[Dict[str, Any]] = None
    ) -> None:
        action = action or {}
        context = context or {}
        self._check_rank(action.get("decision_level"), self.decision_level, DECISION_RANK, "decision authority")
        self._check_rank(action.get("data_classification"), self.data_ceiling, DATA_RANK, "data access")
        self._check_rank(action.get("recipient_scope"), self.comm_scope, COMM_RANK, "external communication")
        self._check_rank(action.get("system_access"), self.system_access, SYSTEM_RANK, "system access")

        if action.get("escalates"):
            self.escalate("Action flagged for escalation by caller.", context)
        if action.get("ambiguous") and "ambiguity" in self._lowered_triggers:
            self.escalate("Escalation trigger matched: ambiguity", context)
        if action.get("out_of_scope") and "scope boundary" in self._lowered_triggers:
            self.escalate("Escalation trigger matched: scope boundary", context)

    def escalate(self, reason: str, context: Optional[Dict[str, Any]] = None) -> None:
        raise EscalationRequired(reason, context or {})

    def _check_rank(
        self, requested_value: Any, allowed_value: str, rank_map: Dict[str, int], boundary: str
    ) -> None:
        requested = self._clean_value(requested_value)
        if not requested:
            return
        requested_rank = rank_map.get(requested)
        allowed_rank = rank_map.get(self._clean_value(allowed_value))
        if requested_rank is None or allowed_rank is None:
            self.escalate(f"Unknown {boundary} value.", {"requested": requested, "allowed": allowed_value})
        if requested_rank > allowed_rank:
            raise AuthorityViolation(
                f"Requested {boundary} '{requested}' exceeds '{allowed_value}'."
            )

    @property
    def _lowered_triggers(self) -> List[str]:
        return [trigger.lower() for trigger in self.escalation_triggers]

    @staticmethod
    def _normalize_triggers(raw_triggers: Any) -> List[str]:
        if isinstance(raw_triggers, list):
            return [str(item).strip("- ").strip() for item in raw_triggers if str(item).strip()]
        if isinstance(raw_triggers, str):
            return [
                line.strip("- ").strip()
                for line in raw_triggers.splitlines()
                if line.strip("- ").strip()
            ]
        return []

    @staticmethod
    def _clean_value(value: Any) -> str:
        return str(value or "").strip().upper()


class ClonehausGovernanceFilter(IFunctionInvocationFilter):
    """Semantic Kernel filter that cancels unauthorized function calls."""

    def __init__(self, authority_context: Dict[str, Any]):
        self.authority_context = authority_context
        self.guard = GovernanceGuard(authority_context)

    async def on_function_invocation(self, context) -> None:
        """Cancel the invocation when governance rules are violated."""

        arguments = getattr(context, "arguments", {}) or {}
        action = {
            "decision_level": arguments.get("decision_level"),
            "data_classification": arguments.get("data_classification"),
            "recipient_scope": arguments.get("recipient_scope"),
            "system_access": arguments.get("system_access"),
            "ambiguous": arguments.get("ambiguous"),
            "out_of_scope": arguments.get("out_of_scope"),
            "escalates": arguments.get("escalates"),
        }

        try:
            self.guard.check_authority(action, {"function": getattr(context, "function_name", None)})
        except (AuthorityViolation, EscalationRequired) as exc:
            context.cancel = True
            context.result = f"ESCALATION: {exc}"
            return

        next_callable = getattr(context, "next", None)
        if next_callable is None:
            return
        result = next_callable()
        if inspect.isawaitable(result):
            await result


if __name__ == "__main__":
    # Example wiring. Replace add_filter with the kernel registration API your
    # installed Semantic Kernel version exposes.
    kernel = Kernel()
    governance_filter = ClonehausGovernanceFilter(DEFAULT_AUTHORITY_CONTEXT)
    if hasattr(kernel, "add_filter"):
        kernel.add_filter(governance_filter)
    print("Semantic Kernel governance filter configured for {{agent_name}}.")
